In [4]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import seaborn as sns
import numpy as np
lbl_encoder=LabelEncoder()

In [5]:
## Simple DataFrame
df=pd.DataFrame({"color":["red","blue","green","green","red","blue"]})

In [6]:
df

,color
0,red
1,blue
2,green
3,green
4,red
5,blue


In [7]:
lbl_encoder.fit_transform(df[["color"]])

c:\Users\agarw\OneDrive\Desktop\Revision\Python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [8]:
lbl_encoder.transform([["red"]])

c:\Users\agarw\OneDrive\Desktop\Revision\Python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [9]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df=pd.DataFrame({"size":["small","medium","large","medium","small","large"]})

In [13]:
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [19]:
# create instance then fit_transform
o_encoder=OrdinalEncoder(categories=[["small","medium","large"]])
o_encoder.fit_transform(df[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [20]:
o_encoder.transform([["small"]])

c:\Users\agarw\OneDrive\Desktop\Revision\Python\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])