# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [8]:
# ### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np

arr1=np.random.randint(1,20,25).reshape(5,5)
print(arr1)
arr2=np.arange(1,17).reshape(4,4)
#arr2-(np.ones(4,4)-np.eye(4,4))
#print(arr2)
print(arr2*(np.ones((4,4),dtype=int)-np.eye(4,4,dtype=int)))

[[ 1  7  9 14 10]
 [14 18  5 15  8]
 [10 19  4 13 10]
 [ 1  8  7  7 10]
 [ 7 18  4 17 13]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [23]:
'''
### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
'''

arr1=np.arange(1,37).reshape(6,6)
print(arr1)
print(arr1[2:5,1:4])

arr2=np.random.randint(1,10,25).reshape(5,5)
print(arr2)
# print(arr2[0])
# print(arr2[4])
# print(arr2[1:4,0])
# print(arr2[1:4,4])
np.concatenate((arr2[0],arr2[1:4,4],arr2[4,-1::-1],arr2[3:0:-1,0]))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[5 2 3 8 5]
 [5 3 3 5 7]
 [5 8 8 1 4]
 [7 5 4 9 3]
 [2 8 8 6 2]]


array([5, 2, 3, 8, 5, 7, 4, 3, 2, 6, 8, 8, 2, 7, 5, 5], dtype=int32)

In [25]:
# ### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. 
# Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr1=np.random.randint(1,20,12).reshape(3,4)
arr2=np.random.randint(1,20,12).reshape(3,4)
print(arr1)
print()
print(arr2)

print("Element Wise Operations :")
print("Addition\n",arr1+arr2)
print("Subtraction\n",arr1-arr2)
print("Multiplication\n",arr1*arr2)
print("Division\n",arr1/arr2)


[[15 12  3 18]
 [ 7 12 15  3]
 [15  1  8 19]]

[[ 5 11 17  1]
 [ 6  1 13 14]
 [12  7 18 19]]
Element Wise Operations :
Addition
 [[20 23 20 19]
 [13 13 28 17]
 [27  8 26 38]]
Subtraction
 [[ 10   1 -14  17]
 [  1  11   2 -11]
 [  3  -6 -10   0]]
Multiplication
 [[ 75 132  51  18]
 [ 42  12 195  42]
 [180   7 144 361]]
Division
 [[ 3.          1.09090909  0.17647059 18.        ]
 [ 1.16666667 12.          1.15384615  0.21428571]
 [ 1.25        0.14285714  0.44444444  1.        ]]


In [27]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print()
print("Columnwise sum :",arr.sum(axis=0))
print("Rowwise sum :",arr.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Columnwise sum : [28 32 36 40]
Rowwise sum : [10 26 42 58]


In [ ]:
# ### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr=np.random.randint(1,10,25).reshape(5,5)
print(arr)
print()
print("Mean",np.mean(arr))
print("Median",np.median(arr))
print("Standard Deviation",np.std(arr))
print("Variance",np.var(arr))


[[6 3 5 6 9]
 [5 6 5 6 6]
 [5 5 5 6 8]
 [7 2 7 6 4]
 [9 3 1 9 1]]

Mean 5.4
Median 6.0
Standard Deviation 2.172556098240043
Variance 4.72


In [30]:
arr=np.arange(1,10).reshape(3,3)
normalization=(arr-(np.ones((3,3))*np.mean(arr)))/np.std(arr)
print(normalization)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [ ]:
# ### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr1=np.random.randint(1,10,9).reshape(3,3)
arr2=np.array([1,2,3])
print(arr1)
print(arr2)

print(arr1+arr2)

arr1=np.random.randint(1,10,16).reshape(4,4)
arr2=np.array([1,2,3,4])
print(arr2[:, np.newaxis])
print()
print(arr1)
print(arr2)

print(np.transpose(np.transpose(arr1)-arr2))


[[8 6 9]
 [1 1 8]
 [4 8 4]]
[1 2 3]
[[ 9  8 12]
 [ 2  3 11]
 [ 5 10  7]]
[[1]
 [2]
 [3]
 [4]]

[[5 5 1 1]
 [5 4 4 6]
 [1 8 9 6]
 [1 5 9 7]]
[1 2 3 4]
[[ 4  4  0  0]
 [ 3  2  2  4]
 [-2  5  6  3]
 [-3  1  5  3]]


In [45]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

arr=np.random.randint(1,10,9).reshape(3,3)
print("Determinant",np.linalg.det(arr))
print("Inverse",np.linalg.inv(arr))
print("Eigen Values",np.linalg.eig(arr))

Determinant 10.999999999999996
Inverse [[ 0.63636364 -0.90909091 -0.18181818]
 [-1.45454545  3.36363636  0.27272727]
 [ 0.18181818 -0.54545455  0.09090909]]
Eigen Values EigResult(eigenvalues=array([11.        ,  3.73205081,  0.26794919]), eigenvectors=array([[-0.58834841, -0.78946276,  0.26988765],
       [-0.19611614, -0.41109374, -0.95020044],
       [-0.78446454,  0.45579654,  0.15581971]]))


In [46]:
arr1=np.arange(1,7).reshape(2,3)
arr2=np.arange(1,7).reshape(3,2)
print("Matrix Multiplication")
print(np.linalg.matmul(arr1,arr2))

Matrix Multiplication
[[22 28]
 [49 64]]


In [54]:
# ### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

arr1=np.arange(1,10).reshape(3,3)
print(arr1)
arr1=arr1.reshape(1,9)
print(arr1)
arr1=arr1.reshape(9,1)
print(arr1)

arr2=np.random.randint(1,20,25).reshape(5,5)
print(arr2)
arr3=arr2.flatten()
print(arr3)
arr3=arr3.reshape(5,5)
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 6  1  2 12  7]
 [ 3 17 17 15 14]
 [15  8  2  1 12]
 [ 6  5 11 17 16]
 [15 11  2 16 18]]
[ 6  1  2 12  7  3 17 17 15 14 15  8  2  1 12  6  5 11 17 16 15 11  2 16
 18]
[[ 6  1  2 12  7]
 [ 3 17 17 15 14]
 [15  8  2  1 12]
 [ 6  5 11 17 16]
 [15 11  2 16 18]]


In [64]:
# ### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. 
# Use fancy indexing to extract the elements at the corners of the array.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.

arr=np.random.randint(1,10,25).reshape(5,5)
print(arr)

print(arr[0,0],arr[0,-1],arr[-1,0],arr[-1,-1])

print(arr[[0,0,-1,-1],[0,-1,0,-1]])


arr2=np.random.randint(1,20,16).reshape(4,4)

arr2[arr2>10]=10

print(arr2)


[[5 7 2 4 9]
 [8 4 3 5 3]
 [3 9 4 2 8]
 [9 9 3 7 5]
 [1 6 9 4 2]]
5 9 1 2
[5 9 1 2]
[[ 7 10 10  6]
 [ 5 10 10 10]
 [ 9  6 10  8]
 [10  7 10  2]]


In [69]:
# ### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). 
# Add some data and sort the array by age.

# 2. Create a structured array with fields 'x' and 'y' (both integers). 
# Add some data and compute the Euclidean distance between each pair of points.

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)

sorted_arr=np.sort(data,order="age")
print(sorted_arr)

[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [73]:
a1=np.array([("Priya",21,80.0),("Rahul",22,85.0)],dtype=[("Name","U10"),("Age","i4"),("Weight","f4")])

In [74]:
print(a1)

[('Priya', 21, 80.) ('Rahul', 22, 85.)]


In [76]:
a1["Name"]

array(['Priya', 'Rahul'], dtype='<U10')

In [83]:
# # 2. Create a structured array with fields 'x' and 'y' (both integers). 
# Add some data and compute the Euclidean distance between each pair of points.

dtype=[("x","i4"),("y","i4")]
arr1=np.array([(1,2),(3,4),(5,6)],dtype=dtype)

print(arr1)
import math
# Euclidean Formula -- sqrt((x1-x2)^2+(y1-y2)^2)
for i in range(len(arr1)):
    for j in range(i+1,len(arr1)):
        print("Distance b/w",arr1[i],"and",arr1[j])
        e=math.sqrt((arr1[i]["x"]-arr1[j]["x"])**2+(arr1[i]["y"]-arr1[j]["y"])**2)
        print("Distance :",e)

[(1, 2) (3, 4) (5, 6)]
Distance b/w (1, 2) and (3, 4)
Distance : 2.8284271247461903
Distance b/w (1, 2) and (5, 6)
Distance : 5.656854249492381
Distance b/w (3, 4) and (5, 6)
Distance : 2.8284271247461903


In [90]:
arr2=arr1['x'][:, np.newaxis]
print(arr2)
arr3=arr1['x']
print(arr3)
print(arr2-arr3)

[[1]
 [3]
 [5]]
[1 3 5]
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]


In [98]:
# ### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. 
# Compute the sum of the unmasked elements.
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. 
# Replace the masked elements with the mean of the unmasked elements.

arr1=np.random.randint(1,20,16).reshape(4,4)
masked_array=np.ma.masked_greater(arr1, 10)
print(masked_array)

sum=masked_array.sum()
print(sum)

arr2=np.random.randint(1,10,9).reshape(3,3)
print(arr2)
masked_dia=np.ma.masked_array(arr2,np.eye(3,3,dtype=bool))
print(masked_dia)

m=masked_dia.mean()
print("Mean Unmasked",m)
filled_arr=masked_dia.filled(m)
print(filled_arr)

[[1 6 8 4]
 [9 -- -- 4]
 [-- 4 -- --]
 [-- 3 7 8]]
54
[[5 3 3]
 [7 6 8]
 [6 4 3]]
[[-- 3 3]
 [7 -- 8]
 [6 4 --]]
Mean Unmasked 5.166666666666667
[[5 3 3]
 [7 5 8]
 [6 4 5]]
